services:
  movie_recommender_agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: movie_recommender_agent
    ports:
      - "3773:3773"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      

    env_file:
      - .env
    volumes:
      - ./movie_recommender_agent:/app/movie_recommender_agent
      - ./agent_config.json:/app/agent_config.json
    restart: unless-stopped
    networks:
      - movie_recommender_agent-network
    

networks:
  movie_recommender_agent-network:
    driver: bridge


